{
    "name": "Symfony\\Component\\HttpFoundation\\File\\Exception\\NoFileException",
    "line": 19,
    "short_desc": "Thrown when an UPLOAD_ERR_NO_FILE error occurred with UploadedFile.",
    "long_desc": "",
    "hint": null,
    "tags": {
        "author": [
            [
                "Florent",
                "Mata",
                "<florentmata@gmail.com>"
            ]
        ]
    },
    "namespace": "Symfony\\Component\\HttpFoundation\\File\\Exception",
    "file": "\/home\/cabox\/workspace\/core\/src\/Khan\/Component\/HttpFoundation\/File\/Exception\/NoFileException.php",
    "relative_file": null,
    "hash": "3a1d18705025b6898aad4f0d45de9241e43a8016",
    "parent": "Symfony\\Component\\HttpFoundation\\File\\Exception\\FileException",
    "modifiers": 0,
    "is_trait": false,
    "is_interface": false,
    "aliases": [],
    "errors": [],
    "interfaces": [],
    "traits": [],
    "properties": [],
    "methods": [],
    "constants": []
}